config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'chatroom#index'
  get 'login', to: 'session#new'
  post 'login', to: 'session#create'
  delete 'logout', to: 'session#destroy'

  post 'message', to: 'messages#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true
    validates :username, uniqueness: { case_sensitive: false }
    validates :username, length: { minimum: 3, maximum: 15 }
    has_many :messages
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action."
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @message = Message.new
    @messages = Message.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user
  
  def create
    message = current_user.messages.build(message_params)
    if message.save
      redirect_to root_path
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(username: params_user_name)
    if user && user.authenticate(params_user_password)
      session[:user_id] = user.id
      flash[:success] = "Logged in succesfully!"
      redirect_to root_path
    else
      flash.now[:error] = " Wrong username or password submited. Try again please!"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash.now[:success] = "You have succesfully Logged Out from the application!"
    render 'new'
  end

  private

  def params_user_name
    params[:session][:username]
  end

  def params_user_password
    params[:session][:password]
  end

  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in."
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<%= render 'layouts/top_main'%> 

<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid wide card chatbox">
      <div class="content">
        <div class="ui feed">
            <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for( @message , html: { class: "ui reply form", role: "form"}, url: message_path ) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body, placeholder: "Enter a message ..." %>
              <%= f.button '<i class="bordered blue large icon telegram"></i>'.html_safe %>
            </div>
          </div>  
        <% end %>
      </div>
    </div>
  </div>
  <div class="four wide column">
    <div class="ui fluid wide card chatbox">
      <div class="content">
        Here
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |type, msg| %>
    <div class="ui <%= type %> mini message transition">
        <i class="close icon"></i>
        <div class="header">
            <%= msg %>
        </div>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui tiny inverted menu">
  <div class="ui container"> 
  <%= link_to "ChatApp", root_path, class: "item" %>
  <a class="item"> Messages </a>
  <div class="right menu">
    <div class="ui dropdown item"> My Account <i class="dropdown icon"></i>
    <div class="menu">
      <% if logged_in? %>
        <%= link_to "Log Out", logout_path, class: "item", method: :delete %>
      <% else %>
        <%= link_to "Log In", login_path, class: "item" %>
      <% end %>
    </div>
    </div>
    <% if !logged_in? %>
      <div class="item">
        <div class="ui primary button"> Sign Up </div>
      </div>
    <% end %>
  </div>
  </div>
</div>

app/views/layouts/_top_main.html.erb
<h2 class="ui center aligned huge icon header">
  <i class="inverted blue  circular users icon"></i>
  ChatApp
</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <div class="ui container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
    <div class="content">
        <div class="summary">
            <em><%= message.user.username %></em> : <%= message.body %>
        </div>
    </div>
</div>

app/views/session/new.html.erb
<%= render 'layouts/top_main'%> 

<div class="ui placeholder segment">
  <div class="ui two column very relaxed stackable grid">
    <div class="column">
      <%= form_for(:session , html: { class: "ui form", role: "form" }, url: login_path ) do |f| %>
        <div class="field">
          <%= f.label :username, "Username" %>
          <div class="ui left icon input">
            <%= f.text_field :username, placeholder: "Enter you username."%>
            <i class="user icon"></i>
          </div>
        </div>
        <div class="field">
          <%= f.label :password, "Password" %>
          <div class="ui left icon input">
            <%= f.password_field :password, placeholder:"Enter you password."%>
            <i class="lock icon"></i>
          </div>
        </div>
        <%= f.button "Login", class: "ui blue submit button" %>
      <% end %>
    </div>
    <div class="middle aligned column">
      <div class="ui big button">
        <i class="signup icon"></i>
        Sign Up
      </div>
    </div>
  </div>
  <div class="ui vertical divider">
    Or
  </div>
</div>